### ISSUE TITLE
Website layout

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#10]
Ticket to discuss all things website layout:

I like the layout however i think the the "Recent Activity" section placement could be improved and we have room to play with the size of the progress map. What do you think about this type of layout? Right now i think it is a little too long (at the moment i can see 11 activities however i think we could get away with 5). If moved to the type of layout in the image, the extra space can potentially be used to expand the length of the trash talk zone.

![image](https://user-images.githubusercontent.com/7059051/34652211-8d34749a-f398-11e7-99c7-5d49065ac76c.png)

**Comment by maryambro** [comment]
I like this, also think the trash talk zone could be a fixed section on the right side (so it would run the entire length of the page) as to see more.

Could the menu currently on the left - search, dashboard, login page - be switched to a side bar/hamburger menu? Or could those items be moved to a different location? Probably not really a need to keep that menu displayed all the time

**Comment by jpdean123** [comment]
I agree with the menu, that will give a lot more space as well. Let me play around with the layout and see what I can do.
