### ISSUE TITLE
Long Page Loading Time

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#15]
If possible: 

Analyze loading time of different components of the webpage to determine the largest factors contributing to the long page loading time. 

For high load components, an idea is to have the page load at a low frequency (e.g. once every 4 hours) but also include a "Manual Refresh" button with proper messaging.
Messaging example: "Individual and Team statistics were upload 1 Hour and 28 Minutes ago, it will automatically be refreshed in 2 Hours and 32 minutes. To manually refresh the page the click <HERE>. Please note that manually refreshing will cause the webpage to momentarily freeze"

**Comment by jpdean123** [comment]
The problem isn't a single component that is causing long load times. Here's how it works:

1. Stored for each 'event' is a list of 'athletes', which includes Strava authentication keys
2. Each time the page loads, the browser downloads the list of athletes
3. Then, for each athlete (21 now), it asks Strava for all activities from that athlete
4. Then, it uses all those activities to create the group stats
5. Then it creates the map
6. Then it creates the chart at the bottom

So its really that we're doing 21 HTTP calls to the Strava API on each page load.

The way to improve this would be to store all listed athletes' activities in my database. Then, each time a new activity is logged the Strava API updates my database with the new event information. That way, we're only pulling one block from a single DB with all the information at once.

**Comment by davfink** [comment]
I like the sound of the solution and can help write out the logic....my contribution to programming it is another question lol

**Comment by jpdean123** [comment]
This is fixed. Google maps still takes some time to load, but there isn't anything I can do about that. It relies on building the map info then asking Google's server to build the map image. Still, a much better load time than previous.
