### ISSUE TITLE
Allow customization of metrics at top of page

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#16]
Allow users to select different number of metrics to be displayed at the top of the page from a selection of metrics.
Example of feature:
User can select between 4 - 8 features to be displayed
User selects from list of 12-15 metrics that can be displayed

Current number of metrics at top of page: 8 
Current list of Metrics at top of page:
1. Goal Miles
2. Current Miles
3. Athletes
4. Days Remaining
5. Time
6. Average Pace
7. Elevation (ft)
8. Days Running

Need to identify additional team fields that might be interesting to see (e.g. % Overall Complete Distance, % Overall Complete Time)

**Comment by jpdean123** [comment]
This would be fairly complex, actually. I think its a good idea but for now, maybe we can just decide what the most important metrics are and have those up for everyone?

**Comment by davfink** [comment]
Agreed that it would be fairly complex and ability to choose is not an MVP feature
