### ISSUE TITLE
Data flow from Strava

### ISSUE THREAD

**Issue by CPFinFarmington** [jpdean123/virtualrelay#21]
Not sure if it's me or my settings. Ran on Thursday, data uploaded to Garmin/Strava, but has yet to find it's way into the Virtual Relay. Is this a YP or a MP?

**Comment by jpdean123** [comment]
Nothing to do with you, I fixed it. For a few days the app was not saving data from Strava. It is updated now.

**Comment by CPFinFarmington** [comment]
Reopening the issue ... seeing double entries and some skipped items.
