### ISSUE TITLE
Decide on a name / domain

### ISSUE THREAD

**Issue by jpdean123** [jpdean123/virtualrelay#22]
Main step from the front-end is to decide on a name and buy a domain for this. Some options / ideas: 

All prices are from Hover.com... there are in no particular order
- My Virtual Relay (myvirtualrelay.com - $12.99)
- Our Virtual Relays (ourvirtualrelays.com - $12.99)
- Cyber Relays (cyberrelays.com $12.99)
- Online Running Club (onlinerunningclub.com - $12.99)
- Laced Up Relays (laceduprelays.com $12.99)
- Virtual Bib Relays (virtualbibrelays.com - $12.99) 
- Virtual Chip Relays (virtualchiprelays.com - $12.99)

Feel free to submit other ideas below

**Comment by jpdean123** [comment]
From Rob- 

Runforestrun
Legsforday
Runmafkrrun
Virutalteamrelay
Customrelay
Yourrelaysite
Buildarelay
Relaysrus
Trainforyourrelay
*virtualteamrelay
Virtualrelay
Relaytime
Bestrelay
Yourpaceormine
Wherethewildthingsrun
Terrarelay

**Comment by jpdean123** [comment]
@davfink the only problem with "My Virtual Relay" is that there is a tool called "My Virtual Mission" which does a very similar thing.

**Comment by davfink** [comment]
Runforestrun
Legsforday
Runmafkrrun
**Virutalteamrelay**
Customrelay
Yourrelaysite
Buildarelay
Relaysrus
Trainforyourrelay
**virtualteamrelay**
**Virtualrelay**
Relaytime
Bestrelay
**Yourpaceormine** (but makes sound like dating app potential haha)
Wherethewildthingsrun
Terrarelay

**Comment by jpdean123** [comment]
Are those the ones you like?

**Comment by davfink** [comment]
**Bolded** are ones that i like however overall im not picky on the name.

**Comment by jpdean123** [comment]
I agree... we can always change it after we get some beta users.
