### ISSUE TITLE
Virtual Pacer stuck on West Coast

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#29]
Virtual pacer has been stuck in San Francisco and does not show progress movement through ocean.

I expect our pacer to demonstrate the same behavior. 

Potentially expect pacers to jump across ocean once mile volume has been reached.

**Comment by davfink** [comment]
Our marker has reached San Fran as well and seems to have stopped at same location. Team progress chart/graph seems to be functioning correctly.

**Comment by jpdean123** [comment]
@davfink Yeah I'm working on it... really a big pain in the ass haha. I spent basically all day yesterday working on it and I'm close.

Problem is, browser has to iterate through every person's list of activities and sum them up to get our current distance. THEN the browser has to get the total distance traveled and calculate the current location. I figured out a better way to do this (store current location in the DB, update it everytime a new activity is logged), its just taking me a while to implement.
