### ISSUE TITLE
"You must be logged in" chat message error when logged in

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#41]
![screen shot 2018-05-13 at 8 31 35 pm](https://user-images.githubusercontent.com/7059051/39975590-c2f9749c-56ec-11e8-93ee-8dc134191245.png)

Cannot send a chat message due to error message "You must be logged in to send a chat message" however when I go to the account icon, i receive a "Logout" option indicating that i am logged in. See screenshot.

**Comment by jpdean123** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Chat logged in check](https://trello.com/c/99dwoI5m/36-chat-logged-in-check)
