### ISSUE TITLE
Strava activity list, future problem

### ISSUE THREAD

**Issue by jpdean123** [jpdean123/virtualrelay#7]
It looks like when pulling each athlete's activities from strava, it only pulls up to 30... most recent 30 perhaps?

For some of the runners, this will be a problem in 5-6 weeks if certain activities are not pulled.

Might have to do some pagination from strava

**Comment by davfink** [comment]
so a historical database will need to be set up and then (if not doesnt already exist) introduce some checking logic so that events are duplicated in the results.

**Comment by jpdean123** [comment]
Fixed
