### ISSUE TITLE
Individual Stats, Group Stats, and Group Chart

### ISSUE THREAD

**Issue by davfink** [jpdean123/virtualrelay#8]
Below are just an initial brainstorming list of metrics. Below list was not created solely for the MVP but more of an end state. With the current code base, i understand that calculating everything would increase web page load times and strategy options (e.g. adjusting stats refresh cadence to a few times per day instead of every website visit, etc.) need to be discussed.

**Individual Metrics**
_Table_
- Number of Activities - Overall
- Distance - Overall
- Time - Overall
- Average Pace - Overall
- Elevation Gained - Overall
- Calories - Overall
- Best Effort Mile - Overall
- Best Effort 5k - Overall
- Number of Activities - Past 7 days
- Distance - Past 7 days
- Time - Past 7 days
- Average Pace - Past 7 days
- Elevation Gained - Past 7 days
- Calories - Past 7 days

**Group Metrics**
_Table_
- Number of Activities - Overall
- Distance - Overall
- Time - Overall
- Elevation Gained - Overall: cool feature would to include comparison against real world items (e.g. "Your team has climbed mt. Everest a total of 3 times!
- Calories - Overall

_Chart_
- Actual Team distance over time
- Targeted Team distance over time
- Regarding the separate "Difference" portion: i dont think the difference portion should be included on the chart because i can see that potentially getting very large and drastically increasing the size of the chart. Ideally teams would be keeping up with the targeted goal.
- Indicating difference by differentiating color - see image
![example team target actual and difference chart](https://user-images.githubusercontent.com/7059051/34651820-dd67b496-f392-11e7-9577-297c5986e7ea.png)

**Comment by davfink** [comment]
Talked to a runner friend and below is list of metrics she said would be cool to see (w/o seeing or being told any of the metrics that we are already providing). Putting here so future reference (if needed)

Pace
Elevation Gain 
Heart Rate 
Cadence
Distance
Calories
Avg Heart Rate
Max Heart Rate 
Time in Zone 
Total Mileage of journey
Mileage comparison between team members
avg pace of all mileage in journey
avg pace of all mileage per individual in journey
city to city segments (showing team segment info vs other team segment info)

**Comment by maryambro** [comment]
Also for individual stats, might be cool to see percentage of overall miles contributed. As in, User A has ran xx% of current total mileage, and xx% of journey mileage

Instead of highlighting the difference between targeted and actual mileage in the graph, adding a hover (or click) feature so that when you hover/click on a data point, a pop up appears that shows exact targeted and actual mileage, as well as the difference

**Comment by davfink** [comment]
@jpdean123 - is it feasible to add in a separate/more in-depth stats page? Obviously there are a lot of cool metrics that can be shown however not all need to be located on the main page so i was thinking about adding a link (e.g. "see more stats here") where a user would select it would would take them to an expanded stats table compared with the "Individual Stats" table that is currently located in the main page.
